// backend/summarizeBatch.js
require('dotenv').config();
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const OPENAI_API_KEY = process.env.GEMINI_API_KEY1;
const USE_MOCK = !OPENAI_API_KEY;

function mockSummary(article) {
  return {
    id: article.id,
    title: article.title,
    summary: `This is a mock summary for: ${article.title}. In production, this will be generated by the LLM using the full article content.`,
    hook: "Mock hook: AI summary coming soon.",
    question: "What do you think about this story?",
    tags: ["mock", "dev"],
  };
}

// ✅ FALLBACK FUNCTIONS - ADDED HERE
function fallbackSummary(article) {
  if (article.description) return article.description.slice(0, 300);
  if (article.rawText) return article.rawText.slice(0, 300);
  return 'Summary temporarily unavailable.';
}

function fallbackHook(article) {
  return article.title || 'Top news update';
}

function fallbackQuestion(article) {
  return 'Why is this news important right now?';
}

async function summarizeArticles() {
  const inPath = path.join(__dirname, 'fetchedArticles.json');
  if (!fs.existsSync(inPath)) {
    console.error("fetchedArticles.json not found. Run fetchNews.js first.");
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(inPath, 'utf8'));
  console.log(`Loaded ${raw.length} articles for summarization.`);

  if (USE_MOCK) {
    console.log("GEMINI_API_KEY missing; using mock summaries.");
    const summaries = raw.map(mockSummary);
    const outPath = path.join(__dirname, 'summaries.json');
    fs.writeFileSync(outPath, JSON.stringify(summaries, null, 2));
    console.log(`Mock summaries saved to ${outPath}`);
    return;
  }

  const summaries = [];
  
  for (const article of raw) {
    console.log(`Summarizing article: ${article.title.slice(0, 50)}...`);
    
    try {
      // ✅ NORMAL GEMINI CALL
      const userPrompt = `
You are a factual news summarizer. For this article, produce:
{
  "summary": "<80-120 words, factual>",
  "hook": "<one witty 6-12 word line>",
  "question": "<one engaging question>"
}

Article: ${JSON.stringify({
  id: article.id,
  title: article.title,
  content: article.content || article.description || "",
})}

Return ONLY valid JSON.
`;

      const response = await axios.post(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${OPENAI_API_KEY}`,
        {
          contents: [{ parts: [{ text: userPrompt }] }],
          generationConfig: { temperature: 0.3 }
        },
        { headers: { "Content-Type": "application/json" } }
      );

      const text = response.data.candidates[0].content.parts[0].text;
      
      // ✅ FIXED JSON extraction
      const jsonMatch = text.match(/\{[\s\S]*\}/);
      let result;
      if (jsonMatch) {
        result = JSON.parse(jsonMatch[0]);
      } else {
        const cleaned = text.replace(/^``````(?:\s*json)?$/, '').trim();
        result = JSON.parse(cleaned);
      }

      summaries.push({
        id: article.id,
        title: article.title,
        title_short: article.title.slice(0, 40) + (article.title.length > 40 ? '...' : ''),
        summary: result.summary,
        hook: result.hook,
        question: result.question,
        tags: ["news", "ai-generated"],
        source: 'gemini',
        articleId: article.id
      });

    } catch (err) {
      // ✅ RATE LIMIT HANDLING
      if (err.response?.status === 429 || err.message.includes('429')) {
        console.warn('[LLM] Rate limit hit, using fallback summary');
        
        summaries.push({
          id: article.id,
          title: article.title,
          title_short: article.title.slice(0, 40) + (article.title.length > 40 ? '...' : ''),
          summary: fallbackSummary(article),  // ✅ Now defined!
          hook: fallbackHook(article),
          question: fallbackQuestion(article),
          tags: ["news", "fallback"],
          source: 'fallback',
          articleId: article.id
        });
        continue;
      }

      // ✅ RETRY LOGIC
      if (err.response?.data?.error?.details) {
        const retryInfo = err.response.data.error.details.find(
          d => d['@type']?.includes('RetryInfo')
        );
        if (retryInfo?.retryDelay) {
          const seconds = parseInt(retryInfo.retryDelay);
          console.log(`[LLM] Retrying in ${seconds}s...`);
          await new Promise(r => setTimeout(r, seconds * 1000));
          
          // Retry once
          try {
            const response = await axios.post(
              `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${OPENAI_API_KEY}`,
              {
                contents: [{ parts: [{ text: userPrompt }] }],
                generationConfig: { temperature: 0.3 }
              },
              { headers: { "Content-Type": "application/json" } }
            );
            
            const text = response.data.candidates[0].content.parts[0].text;
            const jsonMatch = text.match(/\{[\s\S]*\}/);
            let result;
            if (jsonMatch) {
              result = JSON.parse(jsonMatch[0]);
            } else {
              const cleaned = text.replace(/^``````(?:\s*json)?$/, '').trim();
              result = JSON.parse(cleaned);
            }

            summaries.push({
              id: article.id,
              title: article.title,
              title_short: article.title.slice(0, 40) + (article.title.length > 40 ? '...' : ''),
              summary: result.summary,
              hook: result.hook,
              question: result.question,
              tags: ["news", "ai-generated"],
              source: 'gemini-retry',
              articleId: article.id
            });
            continue;
          } catch (retryErr) {
            console.warn('[LLM] Retry failed, using fallback');
          }
        }
      }

      // ✅ FINAL FALLBACK
      console.error(`Failed to summarize article ${article.id}:`, err.message);
      summaries.push({
        id: article.id,
        title: article.title,
        title_short: article.title.slice(0, 40) + (article.title.length > 40 ? '...' : ''),
        summary: fallbackSummary(article),  // ✅ Now defined!
        hook: fallbackHook(article),
        question: fallbackQuestion(article),
        tags: ["news", "fallback"],
        source: 'fallback',
        articleId: article.id
      });
    }
  }

  const outPath = path.join(__dirname, 'summaries.json');
  fs.writeFileSync(outPath, JSON.stringify(summaries, null, 2));
  console.log(`✅ ${summaries.length} summaries saved to ${outPath}`);
  console.log(`Sources: ${summaries.filter(s => s.source === 'gemini' || s.source === 'gemini-retry').length} Gemini, ${summaries.filter(s => s.source === 'fallback').length} fallback`);
}

summarizeArticles();
