// backend/summarizeBatch.js
require('dotenv').config();
const axios = require('axios');
const fs = require('fs');
const path = require('path');

const OPENAI_API_KEY = process.env.GEMINI_API_KEY1;

const USE_MOCK = !OPENAI_API_KEY; // if no key or quota, we mock

function mockSummary(article) {
  return {
    id: article.id,
    title: article.title,
    summary: `This is a mock summary for: ${article.title}. In production, this will be generated by the LLM using the full article content.`,
    hook: "Mock hook: AI summary coming soon.",
    question: "What do you think about this story?",
    tags: ["mock", "dev"],
  };
}

async function summarizeArticles() {
  const inPath = path.join(__dirname, 'fetchedArticles.json');
  if (!fs.existsSync(inPath)) {
    console.error("fetchedArticles.json not found. Run fetchNews.js first.");
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(inPath, 'utf8'));
  console.log(`Loaded ${raw.length} articles for summarization.`);

  if (USE_MOCK) {
    console.log("OPENAI_API_KEY missing or quota issue; using mock summaries.");
    const summaries = raw.map(mockSummary);
    const outPath = path.join(__dirname, 'summaries.json');
    fs.writeFileSync(outPath, JSON.stringify(summaries, null, 2));
    console.log(`Mock summaries saved to ${outPath}`);
    return;
  }

  try {
    const promptArticles = raw.map(a => ({
      id: a.id,
      title: a.title,
      content: a.content || a.description || "",
    }));

    const userPrompt = `
You are a factual news summarizer. For each of the following articles, produce:
{
  "id": "...",
  "title_short": "<10 words max>",
  "summary_80_120": "<80-120 words, factual>",
  "hook": "<one witty 6-12 word line>",
  "question": "<one engaging question>",
  "tags": ["news","..."]
}

Articles:
${JSON.stringify(promptArticles)}
Return ONLY a valid JSON array.
`;

    const response = await axios.post(
      "https://api.openai.com/v1/chat/completions",
      {
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: "You are a helpful news summarizer." },
          { role: "user", content: userPrompt }
        ],
        temperature: 0.3,
      },
      {
        headers: {
          "Authorization": `Bearer ${OPENAI_API_KEY}`,
          "Content-Type": "application/json"
        }
      }
    );

    const text = response.data.choices[0].message.content;
    console.log("RAW MODEL OUTPUT:\n", text);

    let summaries;
    try {
      summaries = JSON.parse(text);
    } catch (e) {
      console.error("Failed to parse JSON from model. Saving raw output.");
      summaries = { raw: text };
    }

    const outPath = path.join(__dirname, 'summaries.json');
    fs.writeFileSync(outPath, JSON.stringify(summaries, null, 2));
    console.log(`Summaries saved to ${outPath}`);

  } catch (err) {
    console.error("Error from OpenAI:", err.response?.data || err.message);
    console.log("Falling back to mock summaries.");
    const summaries = raw.map(mockSummary);
    const outPath = path.join(__dirname, 'summaries.json');
    fs.writeFileSync(outPath, JSON.stringify(summaries, null, 2));
    console.log(`Mock summaries saved to ${outPath}`);
  }
}

summarizeArticles();
